name: Build Site Template

on: 
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Audit NPM
        run: npm audit

      - name: Install NPM dependencies
        run: npm ci

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Site Template
        run: npm run build

      - name: Build Site Template Stub
        run: npm run stub
